---

# Test temporary root password exists

- name: "assert: Stat {{ bsd_mysql_secret_file }}"
  ansible.builtin.stat:
    path: "{{ bsd_mysql_secret_file }}"
  register: my_remote_secret_file

- name: "assert: Debug"
  ansible.builtin.debug:
    msg:
      - "local {{ bsd_mysql_secret_local_file }} exists [{{ bsd_mysql_secret_local_file is exists }}]"
      - "remote {{ bsd_mysql_secret_file }} exists [{{ my_remote_secret_file.stat.exists }}]"
  when: bsd_mysql_debug|bool

- name: "assert: Fail. Version < 8.0"
  block:

# B.4.3.2 How to Reset the Root Password
# https://dev.mysql.com/doc/refman/5.7/en/resetting-permissions.html
# https://dev.mysql.com/doc/refman/8.0/en/resetting-permissions.html
    - name: "assert: HOWTO temporary root password does not exist"
      ansible.builtin.debug:
        msg: "{{ msg.split('\n') }}"
      vars:
        msg: |
          Neither local file {{ bsd_mysql_secret_local_file }}
          nor remote file {{ bsd_mysql_secret_file }} exists.
          Create the file with the temporary root password manually

          shell> service mysql-server stop
          shell> sysrc mysql_args='--skip-grant-tables'
          shell> service mysql-server start
          shell> mysql -u root
          > ALTER USER 'root'@'localhost' IDENTIFIED BY 'newpassword';
          > exit
          shell> service mysql-server stop

          Store the temporary root password in remote file {{ bsd_mysql_secret_file }}.
          Remove mysql_args, start the service and test the existence of the file
          with the new temporary password

          shell> sysrc -x mysql_args
          shell> service mysql-server start
          shell> ansible-playbook playbook.yml -t bsd_mysql_assert

    - name: "assert: Fail. Temporary root password does not exist."
      ansible.builtin.fail:
        msg: "[ERROR] Temporary root password does not exist."
  when:
    - bsd_mysql_version is version('80', '<')
    - bsd_mysql_secret_local_file is not exists
    - not my_remote_secret_file.stat.exists

- name: "assert: Fail. Version >= 8.0"
  block:
    - name: "assert: HOWTO temporary root password does not exist"
      ansible.builtin.debug:
        msg: "{{ msg.split('\n') }}"
      vars:
        msg: |
          Neither local file {{ bsd_mysql_secret_local_file }}
          nor remote file {{ bsd_mysql_secret_file }} exists.
          Create the file with the temporary root password manually

          *************************************************************
          * !!! WARNING: Make sure /var/db/mysql/* can be deleted !!! *
          *************************************************************

          shell> service mysql-server stop
          shell> rm -r /var/db/mysql/*
          shell> sysrc mysql_args='--initialize'
          shell> service mysql-server start

          Find the temporary root password in the log and store it in remote file
          {{ bsd_mysql_secret_file }}. Remove mysql_args, start the service
          and test the existence of the file with the new temporary password

          shell> sysrc -x mysql_args
          shell> service mysql-server start
          shell> ansible-playbook playbook.yml -t bsd_mysql_assert

# Next option is to create a file with the SQL and run it
# B.3.3.2.2 Resetting the Root Password: Unix and Unix-Like Systems
# https://dev.mysql.com/doc/refman/8.0/en/resetting-permissions.html
#
# shell> ls -la /home/.mysql_secret.init
# -rw-------  1 mysql  mysql  57 May 26 20:59 /home/.mysql_secret.init
# shell> cat /home/.mysql_secret.init
# ALTER USER 'root'@'localhost' IDENTIFIED BY 'MyNewPass';
# shell> mysqld_safe --init-file=/home/.mysql_secret.init --user=mysql &

    - name: "assert: Fail. Temporary root password does not exist."
      ansible.builtin.fail:
        msg: "[ERROR] Temporary root password does not exist."
  when:
    - bsd_mysql_version is version('80', '>=')
    - bsd_mysql_secret_local_file is not exists
    - not my_remote_secret_file.stat.exists

# EOF
...
