---

- name: "create_user: Create MySQL users."
  mysql_user:
    config_file: "{{ bsd_mysql_conf_file }}"
    name: "{{ item.user }}"
    login_user: "{{ bsd_mysql_login_user }}"
    login_password: "{{ bsd_mysql_secret }}"
    password: "{{ item.password | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    update_password: "{{ item.update_password | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ bsd_mysql_user }}"
  when: bsd_mysql_enable

# EOF
...
