---

- name: "FreeBSD MySQL Debug."
  vars:
    msg: |
         ansible_architecture [{{ ansible_architecture }}]
         ansible_os_family [{{ ansible_os_family }}]
         ansible_distribution [{{ ansible_distribution }}]
         ansible_distribution_major_version [{{ ansible_distribution_major_version }}]
         ansible_distribution_version [{{ ansible_distribution_version }}]
         ansible_distribution_release [{{ ansible_distribution_release }}]

         bsd_mysql_enable [{{ bsd_mysql_enable }}]
         bsd_mysql_version [{{ bsd_mysql_version }}]
         bsd_mysql_service [{{ bsd_mysql_service }}]
         bsd_mysql_secret_file [{{ bsd_mysql_secret_file }}]
         bsd_mysql_secret_local_file [{{ bsd_mysql_secret_local_file }}]
         bsd_mysql_secret_local_file_mode [{{ bsd_mysql_secret_local_file_mode }}]
         bsd_mysql_conf_path [{{ bsd_mysql_conf_path }}]
         bsd_mysql_conf_file [{{ bsd_mysql_conf_file }}]
         bsd_mysql_bind_address [{{ bsd_mysql_bind_address }}]
         bsd_mysql_port [{{ bsd_mysql_port }}]
         bsd_mysql_login_user [{{ bsd_mysql_login_user }}]
         bsd_mysql_conf_backup [{{ bsd_mysql_conf_backup }}]
         bsd_mysql_conf
         {{ bsd_mysql_conf|to_yaml }}
         bsd_mysql_db
         {{ bsd_mysql_db|to_nice_yaml }}
         freebsd_install_method [{{ freebsd_install_method }}]
         freebsd_use_packages [{{ freebsd_use_packages|default('absent') }}]
         bsd_mysql_packages
         {{ bsd_mysql_packages|to_nice_yaml }}

         {% if bsd_mysql_debug_classified|bool %}
         bsd_mysql_secret [{{ bsd_mysql_secret|default('UNDEFINED') }}]
         bsd_mysql_user
         {{ bsd_mysql_user|to_nice_yaml }}
         {% endif %}
  debug:
    msg: "{{ msg.split('\n') }}"

# EOF
...
