---
- name: "Directories: Create directories, set ownership, and permissions."
  ansible.builtin.file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ bsd_mysql_directories }}"

# EOF
