---

- name: "files: Create files set ownership, and permissions"
  file:
    state: touch
    access_time: preserve
    modification_time: preserve
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ bsd_mysql_files }}"

# EOF
...
