---
- name: "Files: Create files set ownership, and permissions."
  ansible.builtin.file:
    state: touch
    access_time: preserve
    modification_time: preserve
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ bsd_mysql_files }}"

# EOF
