---
# tasks freebsd-mysql

- import_tasks: debug.yml
  when: bsd_mysql_debug
  tags: bsd_mysql_debug

- import_tasks: assert.yml
  tags: [ bsd_mysql_assert, always ]

- import_tasks: packages.yml
  tags: bsd_mysql_packages

- import_tasks: mycnf.yml
  tags: bsd_mysql_mycnf

- import_tasks: rcconf.yml
  tags: bsd_mysql_rcconf

- import_tasks: secret.yml
  tags: bsd_mysql_secret

- import_tasks: create_db.yml
  when: bsd_mysql_enable
  tags: bsd_mysql_create_db

- import_tasks: create_user.yml
  when: bsd_mysql_enable
  tags: bsd_mysql_create_user

# EOF
...
