---
# tasks freebsd_mysql

- import_tasks: directories.yml
  tags: bsd_mysql_directories

- import_tasks: sanity.yml
  when: bsd_mysql_sanity|bool
  tags: bsd_mysql_sanity

- import_tasks: debug.yml
  when: bsd_mysql_debug|bool
  tags: [bsd_mysql_debug, always]

- import_tasks: packages.yml
  when: bsd_mysql_packages|bool
  tags: bsd_mysql_packages

- import_tasks: patches.yml
  when: bsd_mysql_patches|bool
  tags: bsd_mysql_patches

- import_tasks: mycnf.yml
  tags: bsd_mysql_mycnf

- import_tasks: rcconf.yml
  tags: bsd_mysql_rcconf

- import_tasks: assert.yml
  tags: [bsd_mysql_assert, never]

- import_tasks: secret.yml
  tags: [bsd_mysql_secret, never]

- import_tasks: mysql_info.yml
  when: bsd_mysql_info|bool
  tags: bsd_mysql_info

- import_tasks: mysql_db.yml
  when: bsd_mysql_enable|bool
  tags: bsd_mysql_db

- import_tasks: mysql_user.yml
  when: bsd_mysql_enable|bool
  tags: bsd_mysql_user

# EOF
...
