---
# tasks freebsd_mysql

- import_tasks: directories.yml
  tags: bsd_mysql_directories

- import_tasks: files.yml
  tags: bsd_mysql_files

- import_tasks: sanity.yml
  when: bsd_mysql_sanity|bool
  tags: bsd_mysql_sanity

- import_tasks: debug.yml
  when: bsd_mysql_debug|bool
  tags: [bsd_mysql_debug, always]

- import_tasks: packages.yml
  when: bsd_mysql_install|bool
  tags: bsd_mysql_packages

- import_tasks: patches.yml
  when: bsd_mysql_patches|bool
  tags: bsd_mysql_patches

- import_tasks: rmlock.yml
  when: bsd_mysql_rmlock|bool
  tags: bsd_mysql_rmlock

- import_tasks: mycnf.yml
  tags: bsd_mysql_mycnf

- import_tasks: rcconf.yml
  tags: bsd_mysql_rcconf

- import_tasks: assert.yml
  tags: [bsd_mysql_assert, never]

# Warning: Task not idempotent !
# * Run this task '-t bsd_mysql_secret' only once to change temporary
#   password for bsd_mysql_login_user (root).
# * Run '-t bsd_mysql_assert' first to see the status of the passwords
- import_tasks: secret.yml
  tags: [bsd_mysql_secret, never]

- import_tasks: mysql_info.yml
  when: bsd_mysql_info|bool
  tags: bsd_mysql_info

- import_tasks: mysql_db.yml
  when: bsd_mysql_enable|bool
  tags: bsd_mysql_db

- import_tasks: mysql_user.yml
  when: bsd_mysql_enable|bool
  tags: bsd_mysql_user

- import_tasks: mysql_secure_installation.yml
  when: bsd_mysql_secure_installation|bool
  tags: bsd_mysql_secure_installation

# EOF
...
