---
# tasks vbotka.freebsd-mysql

- include: packages.yml
  tags:
    - bsd_packages
    - bsd_ports
    - mysql-packages
    - mysql_all

- include: config_rc_conf.yml
  tags:
    - config_rc_conf
    - mysql-config_rc_conf
    - mysql_all

- include: config_my_cnf.yml
  tags:
    - config_my_cnf
    - mysql-config_my_cnf
    - mysql_all

- include: create_db.yml
  tags:
    - mysql-create-db
    - mysql_all

- include: create_user.yml
  tags:
    - mysql-create-user
    - mysql_all

# EOF
...
