---
# tasks ansible-freebsd-mysql

- include: packages.yml
  tags:
    - packages
    - mysql-packages
    - mysql_all

- include: config_rc_conf.yml
  tags:
    - config_rc_conf
    - mysql-config_rc_conf
    - mysql_all

- include: config_my_cnf.yml
  tags:
    - config_my_cnf
    - mysql-config_httpd_conf
    - mysql_all

# EOF
