---
# tasks freebsd_mysql

- name: "Test supported version of MySQL by this role."
  ansible.builtin.fail:
    msg: "[ERROR] Version {{ bsd_mysql_version }} is not supported by this role.
          Only versions {{ bsd_mysql_supported_versions }} have been tested.
          Update defaults/main.yml to enable other versions. Contributions are
          welcome. See https://github.com/vbotka/ansible-freebsd-mysql"
  when: bsd_mysql_version|int not in bsd_mysql_supported_versions
  tags: [bsd_mysql_version, always]

- name: Import directories.yml
  ansible.builtin.import_tasks: directories.yml
  tags: bsd_mysql_directories

- name: Import files.yml
  ansible.builtin.import_tasks: files.yml
  tags: bsd_mysql_files

- name: Import sanity.yml
  ansible.builtin.import_tasks: sanity.yml
  when: bsd_mysql_sanity|bool
  tags: bsd_mysql_sanity

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: bsd_mysql_debug|bool
  tags: [bsd_mysql_debug, always]

- name: Import packages.yml
  ansible.builtin.import_tasks: packages.yml
  when: bsd_mysql_install|bool
  tags: bsd_mysql_packages

- name: Import patches.yml
  ansible.builtin.import_tasks: patches.yml
  when: bsd_mysql_patches|bool
  tags: bsd_mysql_patches

- name: Import rmlock.yml
  ansible.builtin.import_tasks: rmlock.yml
  when: bsd_mysql_rmlock|bool
  tags: bsd_mysql_rmlock

- name: Import mycnf.yml
  ansible.builtin.import_tasks: mycnf.yml
  tags: bsd_mysql_mycnf

- name: Import rcconf.yml
  ansible.builtin.import_tasks: rcconf.yml
  tags: bsd_mysql_rcconf

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  tags: [bsd_mysql_assert, never]

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   [WARNING] Task secret.yml is not idempotent !
#
# * Run this task '-t bsd_mysql_secret' only once to change temporary
#   password for bsd_mysql_login_user (root).
# * Run '-t bsd_mysql_assert' first to see the status of the passwords
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- name: Import secret.yml
  ansible.builtin.import_tasks: secret.yml
  tags: [bsd_mysql_secret, never]

- name: Import mysql_info.yml
  ansible.builtin.import_tasks: mysql_info.yml
  when: bsd_mysql_info|bool
  tags: bsd_mysql_info

- name: Import mysql_db.yml
  ansible.builtin.import_tasks: mysql_db.yml
  when: bsd_mysql_enable|bool
  tags: bsd_mysql_db

- name: Import mysql_user.yml
  ansible.builtin.import_tasks: mysql_user.yml
  when: bsd_mysql_enable|bool
  tags: bsd_mysql_user

- name: Import mysql_secure_installation.yml
  ansible.builtin.import_tasks: mysql_secure_installation.yml
  when: bsd_mysql_secure_installation|bool
  tags: bsd_mysql_secure_installation

# EOF
...
