---

- name: "named: Copy {{ bsd_mysql_conf_file }}.sample to my.cnf"
  command: "cp {{ bsd_mysql_conf_file }}.sample {{ bsd_mysql_conf_file }}"
  args:
    creates: "{{ bsd_mysql_conf_file }}"

- name: "mycnf: Configure {{ bsd_mysql_conf_file }}"
  lineinfile:
    dest: "{{ bsd_mysql_conf_file }}"
    regexp: "^{{ item.regex }}"
    line: "{{ item.regex }} = {{ item.val }}"
    insertafter: "{{ item.after|default(omit) }}"
    owner: "root"
    group: "mysql"
    mode: "0640"
    backup: "{{ bsd_mysql_conf_backup }}"
    create: true
  loop: "{{ bsd_mysql_conf }}"
  notify: restart mysql

# EOF
...
