---

# TODO
# Complete module parameters
# https://docs.ansible.com/ansible/latest/modules/mysql_db_module.html

- name: "create_db: Debug."
  vars:
    msg: |-
         bsd_mysql_conf_file [{{ bsd_mysql_conf_file }}]
         bsd_mysql_login_user [{{ bsd_mysql_login_user }}]
         bsd_mysql_db
         {{ bsd_mysql_db|to_nice_yaml }}

         {% if bsd_mysql_debug_classified %}
         bsd_mysql_secret [{{ bsd_mysql_secret|default('UNDEFINED') }}]
         {% endif %}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: bsd_mysql_debug|bool

- name: "create_db: Create MySQL databases."
  community.mysql.mysql_db:
    config_file: "{{ bsd_mysql_conf_file }}"
    name: "{{ item.name }}"
    login_user: "{{ bsd_mysql_login_user }}"
    login_password: "{{ bsd_mysql_secret|default(omit) }}"
    login_host: "{{ item.login_host|default(omit) }}"
    login_port: "{{ item.login_port|default(omit) }}"
    login_unix_socket: "{{ item.login_unix_socket|default(omit) }}"
    quick: "{{ item.quick|default(omit) }}"
    single_transaction: "{{ item.single_transaction|default(omit) }}"
    ssl_ca: "{{ item.ssl_ca|default(omit) }}"
    ssl_cert: "{{ item.ssl_cert|default(omit) }}"
    ssl_key: "{{ item.ssl_key|default(omit) }}"
    state: "{{ item.state|default(omit) }}"
    target: "{{ item.target|default(omit) }}"
    collation: "{{ item.collation|default(omit) }}"
    connect_timeout: "{{ item.connect_timeout|default(omit) }}"
    encoding: "{{ item.encoding|default(omit) }}"
  loop: "{{ bsd_mysql_db }}"
  no_log: "{{ not bsd_mysql_debug_classified|bool }}"

# EOF
...
