---
- name: "Packages: Install MySQL packages."
  community.general.pkgng:
    name: "{{ bsd_mysql_packages + bsd_mysql_packages2 }}"
  register: result
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method|lower == "packages"

- name: "Packages: Install MySQL ports."
  community.general.portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ bsd_mysql_packages  + bsd_mysql_packages2 }}"
  register: result
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method|lower == "ports"

# EOF
