---

- name: "packages: Install MySQL packages."
  pkgng:
    name: "{{ item }}"
  loop: "{{ bsd_mysql_packages }}"
  when: freebsd_install_method == "packages"

- name: "packages: Install MySQL ports."
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ bsd_mysql_packages }}"
  when: freebsd_install_method == "ports"

# EOF
...
