---
- name: "Patch: Apply patches"
  ansible.posix.patch:
    src: "{{ item.patch }}"
    dest: "{{ item.dest }}"
    backup: "{{ bsd_mysql_patch_backup }}"
  loop: "{{ bsd_mysql_patches_dict[bsd_mysql_version] | d(bsd_mysql_patches_dict.default) }}"

# EOF
