---

- name: "rcconf: Enable and start MySQL."
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^mysql_enable"
    line: "mysql_enable=\"YES\""
    backup: "{{ bsd_mysql_conf_backup }}"
  notify: enable and start mysql
  when: bsd_mysql_enable|bool

- name: "rcconf: Disable and stop MySQL."
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^mysql_enable"
    line: "mysql_enable=\"NO\""
    backup: "{{ bsd_mysql_conf_backup }}"
  notify: disable and stop mysql
  when: not bsd_mysql_enable|bool

- meta: flush_handlers

- name: "rcconf: Wait for MySQL service at port {{ bsd_mysql_port }}."
  wait_for:
    port: "{{ bsd_mysql_port }}"
  when: bsd_mysql_enable|bool

# EOF
...
