---

# /root/.mysql_secret should be created when mysql-server starts for
# the first time. Let's store the secret in bsd_mysql_secret_local_file.
# See 4.4.2 mysql_install_db — Initialize MySQL Data Directory
# https://dev.mysql.com/doc/refman/5.7/en/mysql-install-db.html
# See 2.10.4 Securing the Initial MySQL Account
# https://dev.mysql.com/doc/refman/8.0/en/default-privileges.html

- name: "secret: Create local directory'{{ bsd_mysql_secret_local_dir }}'"
  file:
    state: directory
    path: "{{ bsd_mysql_secret_local_dir }}"
  delegate_to: localhost

# Store the temporary secret into the file bsd_mysql_secret_local_file
- name: "secret: Create '{{ bsd_mysql_secret_file }}'"
  block:
    - name: "secret: Read temporary password from {{ bsd_mysql_secret_file }}"
      command: tail -1 "{{ bsd_mysql_secret_file }}"
      register: bsd_mysql_secret_temp
      no_log: "{{ not bsd_mysql_debug_classified|bool }}"
    - name: "secret: Set variable bsd_mysql_secret_temp"
      set_fact:
        bsd_mysql_secret_temp: "{{ bsd_mysql_secret_temp.stdout }}"
      no_log: "{{ not bsd_mysql_debug_classified|bool }}"
    - name: "secret: Debug variable bsd_mysql_secret_temp"
      debug:
        msg: "bsd_mysql_secret_temp [{{ bsd_mysql_secret_temp }}]"
      when: bsd_mysql_debug_classified|bool
    - name: "secret: Store bsd_mysql_secret_temp in local file {{ bsd_mysql_secret_local_file }}"
      template:
        src: mysql_secret.j2
        dest: "{{ bsd_mysql_secret_local_file }}"
        owner: "{{ bsd_mysql_secret_local_file_owner }}"
        mode: "{{ bsd_mysql_secret_local_file_mode }}"
      delegate_to: localhost
      no_log: "{{ not bsd_mysql_debug_classified|bool }}"
  when: bsd_mysql_secret_local_file is not exists

# Read temporary password from the local file bsd_mysql_secret_local_file
- name: "secret: Read '{{ bsd_mysql_secret_local_file }}'"
  block:
    - name: "secret: Set bsd_mysql_secret_temp from localhost {{ bsd_mysql_secret_local_file }}"
      set_fact:
        bsd_mysql_secret_temp: "{{ lookup('file', bsd_mysql_secret_local_file) }}"
      no_log: "{{ not bsd_mysql_debug_classified|bool }}"
    - name: "secret: Debug variable bsd_mysql_secret_temp"
      debug:
        msg: "bsd_mysql_secret_temp [{{ bsd_mysql_secret_temp }}]"
      when: bsd_mysql_debug_classified|bool
  when: bsd_mysql_secret_local_file is exists

# Change temporary password for bsd_mysql_login_user (root)
- name: "secret: Change temporary password for '{{ bsd_mysql_login_user }}'"
  block:
    - name: "secret: Block: Change temporary password for '{{ bsd_mysql_login_user }}'"
      mysql_user:
        login_user: "{{ bsd_mysql_login_user }}"
        login_password: "{{ bsd_mysql_secret_temp }}"
        name: "{{ bsd_mysql_login_user }}"
        password: "{{ bsd_mysql_secret }}"
        sql_log_bin: false
      no_log: "{{ not bsd_mysql_debug_classified|bool }}"
  rescue:
    - name: "secret: Rescue change temporary password for '{{ bsd_mysql_login_user }}' failed"
      debug:
        msg: "[ERROR] Change temporary password for '{{ bsd_mysql_login_user }}' failed."
    - name: "secret: HOWTO change temporary password for '{{ bsd_mysql_login_user }}'"
      debug:
        msg: "{{ msg.split('\n') }}"
      vars:
        msg: |
          HOWTO change temporary password for {{ bsd_mysql_login_user }} manually.
          Login with temporary password '{{ bsd_mysql_secret_temp }}'
          and change password to '{{ bsd_mysql_secret }}'

          shell> mysql -u root -p
          > ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ bsd_mysql_secret }}';
          > exit
      when: bsd_mysql_debug_classified|bool

# Optionaly remove the remote file bsd_mysql_secret_file with temporary password
- name: "secret: Remove remote file '{{ bsd_mysql_secret_file }}'"
  file:
    state: absent
    path: "{{ bsd_mysql_secret_file }}"
  when: bsd_mysql_secret_file_remove|bool

# EOF
...
