---
- name: "Vars: Set flavors"
  when:
    - freebsd_flavors_enable|bool
    - ansible_os_family == "FreeBSD"

  # EOF
  block:
    - name: "Vars: Set variables for al_bsd_ports_set_flavor"
      ansible.builtin.set_fact:
        al_bsd_ports_list: "{{ bsd_mysql_packages2 }}"
        al_bsd_ports_flavors: "{{ freebsd_flavors }}"
    - name: "Vars: Set flavor"
      ansible.builtin.include_role:
        name: vbotka.ansible_lib
        tasks_from: al_bsd_ports_set_flavor
    - name: "Vars: Get results"
      ansible.builtin.set_fact:
        bsd_mysql_packages2: "{{ al_bsd_ports_list }}"
