---
# handlers ansible-freebsd-mysql

- name: enable and start mysql
  service: name="{{bsd_mysql_service}}" state="started" enabled="yes"

- name: disable and stop mysql
  service: name="{{bsd_mysql_service}}" state="stopped" enabled="no"

- name: start mysql
  service: name="{{bsd_mysql_service}}" state="started"

- name: stop mysql
  service: name="{{bsd_mysql_service}}" state="stopped"

- name: restart mysql
  service: name="{{bsd_mysql_service}}" state="restarted"
