---
# handlers freebsd-mysql

- name: enable and start mysql
  service:
    name: "{{ bsd_mysql_service }}"
    state: started
    enabled: true

- name: disable and stop mysql
  service:
    name: "{{ bsd_mysql_service }}"
    state: stopped
    enabled: false

- name: start mysql
  service:
    name: "{{ bsd_mysql_service }}"
    state: started

- name: stop mysql
  service:
    name: "{{ bsd_mysql_service }}"
    state: stopped

- name: restart mysql
  service:
    name: "{{ bsd_mysql_service }}"
    state: restarted
  when: bsd_mysql_enable|bool

- name: reload mysql
  service:
    name: "{{ bsd_mysql_service }}"
    state: reloaded
  when: bsd_mysql_enable|bool

# EOF
...
