---
# handlers freebsd_mysql

- name: Enable and start mysql
  ansible.builtin.service:
    name: "{{ bsd_mysql_service }}"
    state: started
    enabled: true

- name: Disable and stop mysql
  ansible.builtin.service:
    name: "{{ bsd_mysql_service }}"
    state: stopped
    enabled: false

- name: Start mysql
  ansible.builtin.service:
    name: "{{ bsd_mysql_service }}"
    state: started

- name: Stop mysql
  ansible.builtin.service:
    name: "{{ bsd_mysql_service }}"
    state: stopped

- name: Restart mysql
  ansible.builtin.service:
    name: "{{ bsd_mysql_service }}"
    state: restarted
  when: bsd_mysql_enable|bool

- name: Reload mysql
  ansible.builtin.service:
    name: "{{ bsd_mysql_service }}"
    state: reloaded
  when: bsd_mysql_enable|bool

# EOF
